apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: applications
  namespace: argocd

spec:
  description: User applications

  sourceRepos:
    - https://github.com/willamep/SelfHost-HA-k3s.git

  destinations:
    - server: https://kubernetes.default.svc
      namespace: '*'

  clusterResourceWhitelist:
    - group: ''
      kind: Namespace

  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
