apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infrastructure
  namespace: argocd

spec:
  description: Infrastructure components

  sourceRepos:
    - https://github.com/willamep/SelfHost-HA-k3s.git
    - https://traefik.github.io/charts
    - ghcr.io/prometheus-community/charts
    - https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/

  destinations:
    - server: https://kubernetes.default.svc
      namespace: '*'

  clusterResourceWhitelist:
    - group: '*'
      kind: '*'

  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'