---
- name: Install nfs-server
  apt:
    name: nfs-kernel-server
    state: present
    update_cache: true
    cache_valid_time: 86400

- name: Create share directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
    owner: nobody
    group: nogroup
  loop: "{{ nfs_share }}"

- name: Add export entries to /etc/exports
  ansible.builtin.blockinfile:
    path: /etc/exports
    block: |
      {% for share in nfs_share %}
      {{ share }} {{ allow_subnet }}(rw,sync,no_subtree_check,all_squash,anonuid=65534,anongid=65534)
      {% endfor %}
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    create: true
    mode: "0644"

### На случай если allow_subnet будет список
# - name: Add export entries to /etc/exports
#   ansible.builtin.blockinfile:
#     path: /etc/exports
#     block: |
#       {% for share in nfs_share %}
#       {% for subnet in allow_subnet %}
#       {{ share }} {{ subnet }}(rw,sync,no_subtree_check,all_squash,anonuid=65534,anongid=65534)
#       {% endfor %}
#       {% endfor %}
#     marker: "# {mark} ANSIBLE MANAGED BLOCK"
#     create: true
#     mode: "0644"
#   notify: Reexport NFS shares

- name: Apply NFS exports
  ansible.builtin.command: exportfs -arv
  changed_when: true

- name: Enable and start nfs-kernel-server
  ansible.builtin.systemd:
    name: nfs-kernel-server
    enabled: true
    state: started
