- name: Добавить Helm-репозиторий nfs-subdir-external-provisioner
  kubernetes.core.helm_repository:
    name: "{{ nfs_provisioner_chart_repo_name }}"
    repo_url: "{{ nfs_provisioner_chart_repo_url }}"

- name: Установить/обновить nfs-subdir-external-provisioner
  kubernetes.core.helm:
    name: "{{ nfs_provisioner_release_name }}"
    chart_ref: "{{ nfs_provisioner_chart_ref }}"
    release_namespace: "{{ nfs_provisioner_namespace }}"
    create_namespace: true
    values:
      nfs:
        server: "{{ nfs_server_ip }}"
        path: "{{ nfs_provisioner_share }}"
      storageClass:
        name: "{{ nfs_provisioner_storage_class }}"
        defaultClass: "{{ nfs_provisioner_default_class }}"
        archiveOnDelete: "false"