apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applications
  namespace: argocd

spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error

  generators:
    - git:
        repoURL: https://github.com/willamep/selfhost-ha-k3s.git
        revision: main
        files:
          - path: kubernetes/applications/*/Source.json

  # 1. БАЗОВЫЙ ШАБЛОН (Для Git-приложений по умолчанию)
  template:
    metadata:
      name: '{{ .path.basename }}'
      annotations:
        argocd.argoproj.io/sync-wave: '{{ default "10" (index . "wave") }}'
    spec:
      project: applications

      source:
        repoURL: '{{ default "https://github.com/willamep/selfhost-ha-k3s.git" (index . "repoURL") }}'
        targetRevision: '{{ default "main" (index . "targetRevision") }}'
        path: '{{ default .path.path (index . "sourcePath") }}'
        directory:
          exclude: Source.json

      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ .path.basename }}'

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

  # 2. ДИНАМИЧЕСКИЙ СТРУКТУРНЫЙ ПАТЧ (Для Helm и дополнительных sync options)
  templatePatch: |
    {{- if or (eq .type "helm") (index . "serverSideApply") }}
    spec:
      {{- if eq .type "helm" }}
      source: null
      sources:
        - repoURL: '{{ .repoURL }}'
          chart: '{{ .chart }}'
          targetRevision: '{{ .targetRevision }}'
          helm:
            ignoreMissingValueFiles: true
            valueFiles:
              - $values/{{ .path.path }}/values.yaml

        - repoURL: https://github.com/willamep/selfhost-ha-k3s.git
          targetRevision: main
          ref: values

        {{- if and (index . "hasManifests") .hasManifests }}
        - repoURL: https://github.com/willamep/selfhost-ha-k3s.git
          targetRevision: main
          path: '{{ .path.path }}/manifests'
        {{- end }}
      {{- end }}

      {{- if (index . "serverSideApply") }}
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
      {{- end }}
    {{- end }}
