apiVersion: v1
kind: ConfigMap
metadata:
  name: external-targets-cm
  namespace: monitoring
data:
  targets.json: |
    [
      {
        "targets": [
          "192.168.3.206:9100"
        ],
        "labels": {
          "job": "nextcloud",
          "host": "nextcloud-1"
        }
      },
      {
        "targets": [
          "192.168.3.205:9100"
        ],
        "labels": {
          "job": "nfs_server",
          "host": "nfs-server-1"
        }
      },
      {
        "targets": [
          "192.168.3.207:9100"
        ],
        "labels": {
          "job": "victoriametrics",
          "host": "victoriametrics-1"
        }
      },
      {
        "targets": [
          "192.168.3.204:9100"
        ],
        "labels": {
          "job": "wireguard",
          "host": "wireguard-1"
        }
      },
      {
        "targets": [
          "192.168.3.20:9100",
          "192.168.3.100:9100",
          "192.168.3.200:9100"
        ],
        "labels": {
          "job": "proxmox",
          "env": "hypervisors"
        }
      }
    ]
