---
# Процесс установки
- name: Check current K3s version
  ansible.builtin.command: /usr/local/bin/k3s --version
  register: k3s_current_version_cmd
  failed_when: false
  changed_when: false

- name: Check whether K3s server service is installed
  ansible.builtin.stat:
    path: /etc/systemd/system/k3s.service
  register: k3s_server_service

- name: Set facts for installation condition
  ansible.builtin.set_fact:
    needs_k3s_install: >-
      {{
        k3s_current_version_cmd.rc != 0 or
        not k3s_server_service.stat.exists or
        k3s_version not in k3s_current_version_cmd.stdout
      }}

- name: Deploy kube-vip control-plane VIP
  ansible.builtin.include_tasks: kube-vip.yml

- name: Fetch k3s install script
  ansible.builtin.get_url:
    url: https://get.k3s.io
    dest: /tmp/install-k3s.sh
    mode: "0755"
  when: needs_k3s_install

- name: Bootstrap init server (cluster-init)
  ansible.builtin.include_tasks: init.yml
  when:
    - needs_k3s_install
    - inventory_hostname == k3s_init_host

- name: Join additional servers
  ansible.builtin.include_tasks: join.yml
  when:
    - needs_k3s_install
    - inventory_hostname != k3s_init_host

- name: Ensure K3s server service is enabled and running
  ansible.builtin.systemd_service:
    name: k3s
    enabled: true
    state: started
    daemon_reload: true

- name: Delete k3s installer
  ansible.builtin.file:
    path: /tmp/install-k3s.sh
    state: absent

# Добавление конфига на хотст с ansible для удобного управления helm и kubectl
- name: Fetch kubeconfig from k3s server
  ansible.builtin.fetch:
    src: /etc/rancher/k3s/k3s.yaml
    dest: "{{ localhost_kubeconfig }}"
    flat: true
  delegate_to: "{{ groups['servers'][0] }}"
  run_once: true

- name: Fix server address in local kubeconfig (127.0.0.1 -> real IP)
  ansible.builtin.replace:
    path: "{{ localhost_kubeconfig }}"
    regexp: 'https://127\.0\.0\.1:6443'
    replace: "https://{{ kube_vip_address }}:6443"
  delegate_to: localhost
  become: false
  run_once: true
